
services:
  # 1. UserService
  userservice:
    build:
      context: .
      dockerfile: src/UserService/UserService.Api/Dockerfile
    container_name: userservice
    environment:
      ConnectionStrings__UserServiceConnection: Id=postgres.onbidmrocixrmfdvrolv;Password=0328802216Zz.;Server=aws-1-ap-south-1.pooler.supabase.com;Port=5432;Database=postgres;SslMode=Require;Timeout=30;
      Jwt__Key: BookbridgeJWTKey_2025_Secure_ABC123!
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5141:8080"

  # 6. Redis cache
  redis:
    image: redis:7.2
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgadmin_data:
